/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static t8p2e1.T8P2E1.abrirError;

/**
 *
 * @author Luyan
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAbogado = new javax.swing.JMenu();
        mAltaAbogado = new javax.swing.JMenuItem();
        mBajaAbogado = new javax.swing.JMenuItem();
        mModificarAbogado = new javax.swing.JMenuItem();
        mConsultaAbogado = new javax.swing.JMenuItem();
        mCliente = new javax.swing.JMenu();
        mAltaCliente = new javax.swing.JMenuItem();
        mBajaCliente = new javax.swing.JMenuItem();
        mModificarCliente = new javax.swing.JMenuItem();
        mConsultaCliente = new javax.swing.JMenuItem();
        mCaso = new javax.swing.JMenu();
        mAltaCaso = new javax.swing.JMenuItem();
        mBajaCaso = new javax.swing.JMenuItem();
        mModificarCaso = new javax.swing.JMenuItem();
        mConsultaCaso = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fondoInicio.jpg"))); // NOI18N

        mAbogado.setText("Abogados");

        mAltaAbogado.setText("Alta");
        mAbogado.add(mAltaAbogado);

        mBajaAbogado.setText("Baja");
        mAbogado.add(mBajaAbogado);

        mModificarAbogado.setText("Modificar");
        mAbogado.add(mModificarAbogado);

        mConsultaAbogado.setText("Consulta");
        mAbogado.add(mConsultaAbogado);

        jMenuBar1.add(mAbogado);

        mCliente.setText("Clientes");

        mAltaCliente.setText("Alta");
        mAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltaClienteActionPerformed(evt);
            }
        });
        mCliente.add(mAltaCliente);

        mBajaCliente.setText("Baja");
        mBajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBajaClienteActionPerformed(evt);
            }
        });
        mCliente.add(mBajaCliente);

        mModificarCliente.setText("Modificar");
        mModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificarClienteActionPerformed(evt);
            }
        });
        mCliente.add(mModificarCliente);

        mConsultaCliente.setText("Consulta");
        mConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaClienteActionPerformed(evt);
            }
        });
        mCliente.add(mConsultaCliente);

        jMenuBar1.add(mCliente);

        mCaso.setText("Casos");

        mAltaCaso.setText("Alta");
        mCaso.add(mAltaCaso);

        mBajaCaso.setText("Baja");
        mCaso.add(mBajaCaso);

        mModificarCaso.setText("Modificación");
        mCaso.add(mModificarCaso);

        mConsultaCaso.setText("Consulta");
        mCaso.add(mConsultaCaso);

        jMenuBar1.add(mCaso);

        menusalir.setText("Salir");

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        menusalir.add(mSalir);

        jMenuBar1.add(menusalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        t8p2e1.T8P2E1.finalizar();
    }//GEN-LAST:event_mSalirActionPerformed

    private void mBajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBajaClienteActionPerformed
        try
        {
            t8p2e1.T8P2E1.abrirBaja(true);
            dispose();
        }
        catch(Exception e)
        {
            t8p2e1.T8P2E1.abrirError(e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mBajaClienteActionPerformed

    private void mAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltaClienteActionPerformed
        try
        {
            t8p2e1.T8P2E1.abrirAlta(true);
            dispose();
        }
        catch(Exception e)
        {
            t8p2e1.T8P2E1.abrirError(e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mAltaClienteActionPerformed

    private void mModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificarClienteActionPerformed
        try
        {
            //t8p2e1.T8P2E1.abrirModificar(true);
            dispose();
        }
        catch(Exception e)
        {
            t8p2e1.T8P2E1.abrirError(e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mModificarClienteActionPerformed

    private void mConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaClienteActionPerformed
        try
        {
            //t8p2e1.T8P2E1.abrirConsulta(true);
            dispose();
        }
        catch(Exception e)
        {
            t8p2e1.T8P2E1.abrirError(e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mConsultaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAbogado;
    private javax.swing.JMenuItem mAltaAbogado;
    private javax.swing.JMenuItem mAltaCaso;
    private javax.swing.JMenuItem mAltaCliente;
    private javax.swing.JMenuItem mBajaAbogado;
    private javax.swing.JMenuItem mBajaCaso;
    private javax.swing.JMenuItem mBajaCliente;
    private javax.swing.JMenu mCaso;
    private javax.swing.JMenu mCliente;
    private javax.swing.JMenuItem mConsultaAbogado;
    private javax.swing.JMenuItem mConsultaCaso;
    private javax.swing.JMenuItem mConsultaCliente;
    private javax.swing.JMenuItem mModificarAbogado;
    private javax.swing.JMenuItem mModificarCaso;
    private javax.swing.JMenuItem mModificarCliente;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenu menusalir;
    // End of variables declaration//GEN-END:variables
}
