/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Excepciones.DatoNoValido;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author 1gdaw05
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    ArrayList<JRadioButton> listaCuentas = new ArrayList();
    int optMovimiento;
    public Menu() {
        initComponents();
        pCuentas.setVisible(false);
        pConsulta.setVisible(false);
        pMovimientos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCuentas = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        bMovimientos = new javax.swing.JButton();
        bConsulta = new javax.swing.JButton();
        pCuentas = new javax.swing.JLayeredPane();
        pMovimientos = new javax.swing.JPanel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        tfCuentaDestino = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfImporte = new javax.swing.JFormattedTextField();
        bAceptar = new javax.swing.JButton();
        tfCodRecibo = new javax.swing.JFormattedTextField();
        pConsulta = new javax.swing.JPanel();
        lbM1 = new javax.swing.JLabel();
        lbM2 = new javax.swing.JLabel();
        lbM3 = new javax.swing.JLabel();
        lbM4 = new javax.swing.JLabel();
        lbM5 = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        ss = new javax.swing.JMenu();
        mConsulta = new javax.swing.JMenu();
        mMovimientos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/movimientos.JPG"))); // NOI18N
        bMovimientos.setFocusable(false);
        bMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMovimientos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMovimientosActionPerformed(evt);
            }
        });
        jToolBar1.add(bMovimientos);

        bConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/consulta.JPG"))); // NOI18N
        bConsulta.setFocusable(false);
        bConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultaActionPerformed(evt);
            }
        });
        jToolBar1.add(bConsulta);

        pCuentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuentas"));

        javax.swing.GroupLayout pCuentasLayout = new javax.swing.GroupLayout(pCuentas);
        pCuentas.setLayout(pCuentasLayout);
        pCuentasLayout.setHorizontalGroup(
            pCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1351, Short.MAX_VALUE)
        );
        pCuentasLayout.setVerticalGroup(
            pCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        pMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRANSFERENCIA", "INGRESO", "PAGO RECIBO" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo");

        lbId.setText("Cuenta Destino");

        try {
            tfCuentaDestino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Importe");

        tfImporte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMovimientosLayout = new javax.swing.GroupLayout(pMovimientos);
        pMovimientos.setLayout(pMovimientosLayout);
        pMovimientosLayout.setHorizontalGroup(
            pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMovimientosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAceptar)
                .addGap(45, 45, 45))
            .addGroup(pMovimientosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lbId)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCodRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbTipo, 0, 341, Short.MAX_VALUE)
                        .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCuentaDestino, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pMovimientosLayout.setVerticalGroup(
            pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMovimientosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(48, 48, 48)
                .addGroup(pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(tfCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCodRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAceptar)
                .addGap(91, 91, 91))
        );

        pConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        lbM1.setText("m1");

        lbM2.setText("m2");

        lbM3.setText("m3");

        lbM4.setText("m4");

        lbM5.setText("m5");

        lbSaldo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbSaldo.setText("SALDO: ####");

        javax.swing.GroupLayout pConsultaLayout = new javax.swing.GroupLayout(pConsulta);
        pConsulta.setLayout(pConsultaLayout);
        pConsultaLayout.setHorizontalGroup(
            pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSaldo)
                .addGap(29, 29, 29))
            .addGroup(pConsultaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbM5, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbM1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addComponent(lbM2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbM3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbM4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pConsultaLayout.setVerticalGroup(
            pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsultaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbM1)
                .addGap(18, 18, 18)
                .addComponent(lbM2)
                .addGap(18, 18, 18)
                .addComponent(lbM3)
                .addGap(18, 18, 18)
                .addComponent(lbM4)
                .addGap(18, 18, 18)
                .addComponent(lbM5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Resumen");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tarjetas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inversiones");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Mercados");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Prestamos");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Seguros");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Servicios");
        jMenuBar1.add(jMenu8);

        ss.setText("Cuentas");

        mConsulta.setText("Consulta");
        mConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaActionPerformed(evt);
            }
        });
        ss.add(mConsulta);

        mMovimientos.setText("Movimientos");
        mMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMovimientosActionPerformed(evt);
            }
        });
        ss.add(mMovimientos);

        jMenuBar1.add(ss);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1385, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(pConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCuentas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCuentas)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMovimientosActionPerformed
        mMovimientos.doClick();
    }//GEN-LAST:event_bMovimientosActionPerformed

    private void bConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultaActionPerformed
        mConsulta.doClick();
    }//GEN-LAST:event_bConsultaActionPerformed

    private void mConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaActionPerformed
        try
        {
            llenarCuentas(Main.Main.datosCuentas());
            pCuentas.setVisible(true);
        }
        catch(Exception e)
        {
            Main.Main.error("ERROR: " + e.getClass() + " " + e.getMessage());
        }
    }//GEN-LAST:event_mConsultaActionPerformed

    private void mMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMovimientosActionPerformed
        try
        {
            llenarCuentas(Main.Main.datosCuentas());
            pMovimientos.setVisible(true);
        }
        catch(Exception e)
        {
            Main.Main.error("ERROR: " + e.getClass() + " " + e.getMessage());
        }
    }//GEN-LAST:event_mMovimientosActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        optMovimiento = cbTipo.getSelectedIndex();
        switch(optMovimiento){
            case 1: lbId.setText("Cuenta Destino");
                    break;
            case 2: lbId.setText("Cuenta Seleccionada");
                    break;
            case 3: lbId.setText("Número Recibo");
                    tfCuentaDestino.setVisible(false);
                    tfCodRecibo.setVisible(true);
                    break;
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try
        {
            if(optMovimiento == 3)
            {
                if(tfCodRecibo.getText().isEmpty())
                {
                    throw new DatoNoValido("Codigo Recibo Vacio");
                }
            }
            else
            {
                if(tfCuentaDestino.getText().isEmpty())
                {
                    throw new DatoNoValido("Numero de Cuenta vacio");
                }
            }
            
            if(tfImporte.getText().isEmpty())
            {
                throw new DatoNoValido("Importe Vacio");
            }
            
            if(optMovimiento != 2)
            {
                if(Double.parseDouble(tfImporte.getText()) > Double.parseDouble(Main.Main.datoSaldo()))
                {
                    throw new DatoNoValido("Saldo insuficiente");
                }
            }
            
            switch(optMovimiento){
            case 1: Main.Main.registrarTransferencia(tfCuentaDestino.getText(), tfImporte.getText());
                    break;
            case 2: Main.Main.registrarIngreso(tfImporte.getText());
                    break;
            case 3: Main.Main.registrarPagoRecibo(tfCodRecibo.getText(), tfImporte.getText());
                    break;
            }
            
            tfCodRecibo.setText("");
            tfImporte.setText("");
            tfCuentaDestino.setText("");
            
        }
        catch(DatoNoValido e)
        {
            Main.Main.error(e.getMensaje());
        }
        catch(Exception e)
        {
            Main.Main.error("ERROR: " + e.getClass() + " " + e.getMessage());
        }
    }//GEN-LAST:event_bAceptarActionPerformed
    
    private void rbCuentaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try
        {
            boolean encontrado = false;
            for( int x = 0; x < listaCuentas.size() && encontrado == false; x++)
            {
                if(listaCuentas.get(x).isSelected())
                {
                    Main.Main.setCuentaActual(listaCuentas.get(x).getText());
                    encontrado = true;
                }
            }
            if(pConsulta.isVisible())
            {
                llenarConsultas(Main.Main.datosConsulta());
                pConsulta.setVisible(true);
            }
            
        }
        catch(Exception e)
        {
            Main.Main.error("ERROR: " + e.getClass() + " " + e.getMessage());
        }
        
    }
    
    public void llenarConsultas (ArrayList<String> listaMovimientos) throws Exception{
        ArrayList<JLabel> listaLabel = new ArrayList();
        listaLabel.add(lbM1);
        listaLabel.add(lbM2);
        listaLabel.add(lbM3);
        listaLabel.add(lbM4);
        listaLabel.add(lbM5);
        for(int x = 0; x < listaMovimientos.size(); x++)
        {
            listaLabel.get(x).setText(listaMovimientos.get(x));
        }
        lbSaldo.setText(Main.Main.datoSaldo());
    }
    
    public void llenarCuentas(ArrayList<String> datos) throws Exception{
        pCuentas = new javax.swing.JLayeredPane();
        bgCuentas = new javax.swing.ButtonGroup();
        
        for(int x = 0; x < datos.size(); x++)
        {
            
            listaCuentas.add(new JRadioButton());
            listaCuentas.get(x).setText(datos.get(x));
            listaCuentas.get(x).addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuentaActionPerformed(evt);
            }
            });
            
            bgCuentas.add(listaCuentas.get(x));
            
            pCuentas.setLayer(listaCuentas.get(x), javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        
            javax.swing.GroupLayout pCuentasLayout = new javax.swing.GroupLayout(pCuentas);
            pCuentas.setLayout(pCuentasLayout);
            pCuentasLayout.setHorizontalGroup(

                pCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCuentasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(31, 31, 31)
                    .addGroup(pCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(listaCuentas.get(x))));



                pCuentasLayout.setVerticalGroup(
                pCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCuentasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(listaCuentas.get(x))
                    .addGap(18, 18, 18)
                    .addContainerGap(20, Short.MAX_VALUE)));
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bConsulta;
    private javax.swing.JButton bMovimientos;
    private javax.swing.ButtonGroup bgCuentas;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbM1;
    private javax.swing.JLabel lbM2;
    private javax.swing.JLabel lbM3;
    private javax.swing.JLabel lbM4;
    private javax.swing.JLabel lbM5;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JMenu mConsulta;
    private javax.swing.JMenu mMovimientos;
    private javax.swing.JPanel pConsulta;
    private javax.swing.JLayeredPane pCuentas;
    private javax.swing.JPanel pMovimientos;
    private javax.swing.JMenu ss;
    private javax.swing.JFormattedTextField tfCodRecibo;
    private javax.swing.JFormattedTextField tfCuentaDestino;
    private javax.swing.JFormattedTextField tfImporte;
    // End of variables declaration//GEN-END:variables
}
