/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Luyan
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bAlta = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bModficar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mAlta = new javax.swing.JMenuItem();
        mCancelar = new javax.swing.JMenuItem();
        mModificar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mConfirmacion = new javax.swing.JMenuItem();
        mListado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bAlta.setText("ALTA");
        bAlta.setFocusable(false);
        bAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAlta);

        bCancelar.setText("CANCELACION");
        bCancelar.setFocusable(false);
        bCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(bCancelar);

        bModficar.setText("MODIFICAR");
        bModficar.setFocusable(false);
        bModficar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModficar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bModficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModficarActionPerformed(evt);
            }
        });
        jToolBar1.add(bModficar);

        jMenu1.setText("Eventos");

        mAlta.setText("Alta");
        mAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltaActionPerformed(evt);
            }
        });
        jMenu1.add(mAlta);

        mCancelar.setText("Cancelar");
        mCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCancelarActionPerformed(evt);
            }
        });
        jMenu1.add(mCancelar);

        mModificar.setText("Modificar");
        mModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificarActionPerformed(evt);
            }
        });
        jMenu1.add(mModificar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Asistentes");

        mConfirmacion.setText("Confirmacion");
        mConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConfirmacionActionPerformed(evt);
            }
        });
        jMenu2.add(mConfirmacion);

        mListado.setText("Listado");
        mListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mListadoActionPerformed(evt);
            }
        });
        jMenu2.add(mListado);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaActionPerformed
        mAlta.doClick();
    }//GEN-LAST:event_bAltaActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        mCancelar.doClick();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bModficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModficarActionPerformed
        mModificar.doClick();
    }//GEN-LAST:event_bModficarActionPerformed

    private void mAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltaActionPerformed
        try{
            t8p1e2.Controlador.abrirAlta();
            dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mAltaActionPerformed

    private void mCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCancelarActionPerformed
        try{
            t8p1e2.Controlador.abrirCancelar();
            dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mCancelarActionPerformed

    private void mModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificarActionPerformed
         try{
            t8p1e2.Controlador.abrirModificar();
            dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mModificarActionPerformed

    private void mConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConfirmacionActionPerformed
        try{    
            t8p1e2.Controlador.abrirConfirmacion();
            dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mConfirmacionActionPerformed

    private void mListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mListadoActionPerformed
        try{
            t8p1e2.Controlador.abrirListado();
            dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getClass() + " : " + e.getMessage());
        }
    }//GEN-LAST:event_mListadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlta;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bModficar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mAlta;
    private javax.swing.JMenuItem mCancelar;
    private javax.swing.JMenuItem mConfirmacion;
    private javax.swing.JMenuItem mListado;
    private javax.swing.JMenuItem mModificar;
    // End of variables declaration//GEN-END:variables
}
